
export const videos = [
    {
        id: 1,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Introducción a la Cinemática",
        description: "U1 - E(1,2,3)",
        subject: "Fisica 1",
    },
    {
        id: 2,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Leyes de Newton",
        description: "U2 - E(4,5,6)",
        subject: "Fisica 1",
    },
    {
        id: 3,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Trabajo y Energía",
        description: "U3 - E(7,8,9)",
        subject: "Fisica 1",
    },
    {
        id: 4,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Leyes de Conservación",
        description: "U4 - E(10,11,12)",
        subject: "Fisica 1",
    },
    {
        id: 5,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Cálculo Diferencial",
        description: "U1 - E(13,14,15)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 6,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Integrales Definidas",
        description: "U2 - E(16,17,18)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 7,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Ecuaciones Diferenciales",
        description: "U3 - E(19,20,21)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 8,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Series de Fourier",
        description: "U4 - E(22,23,24)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 9,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Matrices y Determinantes",
        description: "U1 - E(25,26,27)",
        subject: "Algebra",
    },
    {
        id: 10,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Espacios Vectoriales",
        description: "U2 - E(28,29,30)",
        subject: "Algebra",
    },
    {
        id: 11,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Cinemática del Movimiento Circular",
        description: "U5 - E(31,32,33)",
        subject: "Fisica 1",
    },
    {
        id: 12,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Momento Lineal y Angular",
        description: "U6 - E(34,35,36)",
        subject: "Fisica 1",
    },
    {
        id: 13,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Integral de Línea",
        description: "U3 - E(37,38,39)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 14,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Cálculo de Volúmenes",
        description: "U4 - E(40,41,42)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 15,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Autovalores y Autovectores",
        description: "U3 - E(43,44,45)",
        subject: "Algebra",
    },
    {
        id: 16,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Diagonalización de Matrices",
        description: "U4 - E(46,47,48)",
        subject: "Algebra",
    },
    {
        id: 17,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Conservación de la Energía",
        description: "U7 - E(49,50,51)",
        subject: "Fisica 1",
    },
    {
        id: 18,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Vectores y Producto Escalar",
        description: "U8 - E(52,53,54)",
        subject: "Fisica 1",
    },
    {
        id: 19,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Integrales Múltiples",
        description: "U5 - E(55,56,57)",
        subject: "Analisis Matematico 1",
    },
    {
        id: 20,
        src: "https://drive.google.com/file/d/1yWaUj6oitRIM_M1PMN7eTloO77eihHel/preview",
        title: "Determinantes y Submatrices",
        description: "U6 - E(58,59,60)",
        subject: "Algebra",
    },
];
